language: ruby
rvm:
  - 2.1.2
bundler_args: --without production
before_install:
  - gem update --system
  - gem --version
group: stable
dist: trusty
os: linux
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3